spring.application.name=quiz

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/quizdb

spring.datasource.username=postgres

spring.datasource.password=taka3677

# 起動時に自動でschema.sqlを実行して初期化する設定
spring.sql.init.mode=always


